language: python
dist: xenial
python:
  - "3.5"

# command to install testing dependencies
install:
  - pip install nose

script:
  - python setup.py nosetests
notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
