language: python
dist: xenial
python:
  - "3.5"

# command to install testing dependencies
install:
  - pip install nose

before_script:
  - git clone https://github.com/FNNDSC/ChRIS_ultron_backEnd
  - cd ChRIS_ultron_backEnd
  - ./docker-make.sh -U -I -i
  - cd ../

script:
  - python setup.py nosetests

notifications:
  slack: fnndsc:gGPIVAOtMikWomA1EKrVYIjO
